name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lms-dependency-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install Redis
        run: sudo apt-get install redis-server -y

      - name: Build with Maven
        run: mvn clean install 

      - name: Generate Scoverage report for enrolment-actor
        run: cd course-mw/enrolment-actor && mvn scoverage:report

      - name: Generate Scoverage report for cache-utils
        run: cd course-mw/sunbird-util/cache-utils && mvn scoverage:report

      - name: Build Play Framework distribution
        run: cd service && mvn play2:dist

      - name: Cache Maven dependencies (post-build)
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lms-dependency-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      # - name: SonarQube Analysis
      #   run: |
      #     JAVA_REPORT_PATHS=$(find $GITHUB_WORKSPACE -iname jacoco.xml | paste -sd ",")
      #     mvn verify -DskipTests=true sonar:sonar \
      #       -Dsonar.projectKey=project-sunbird_sunbird-course-service \
      #       -Dsonar.organization=project-sunbird \
      #       -Dsonar.host.url=https://sonarcloud.io \
      #       -Dsonar.coverage.exclusions=**/sunbird-util/sunbird-platform-core/**,**/course-actors-common/** \
      #       -Dsonar.scala.coverage.reportPaths=$GITHUB_WORKSPACE/course-mw/enrolment-actor/target/scoverage.xml,$GITHUB_WORKSPACE/course-mw/sunbird-util/cache-utils/target/scoverage.xml \
      #       -Dsonar.coverage.jacoco.xmlReportPaths=${JAVA_REPORT_PATHS}
