name: pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis:latest
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: maven-dependency-cache-${{ hashFiles('**/pom.xml') }}

      - name: Update apt packages
        run: sudo apt update

      - name: Install Redis server
        run: sudo apt install redis-server -y

      - name: Build the code
        run: mvn clean install -DCLOUD_STORE_GROUP_ID=${{ secrets.CLOUD_STORE_GROUP_ID }} -DCLOUD_STORE_ARTIFACT_ID=${{ secrets.CLOUD_STORE_ARTIFACT_ID }} -DCLOUD_STORE_VERSION=${{ secrets.CLOUD_STORE_VERSION }}

      - name: Generate coverage report for enrolment-actor
        run: |
          cd course-mw/enrolment-actor
          mvn scoverage:report

      - name: Generate coverage report for cache-utils
        run: |
          cd course-mw/sunbird-util/cache-utils
          mvn scoverage:report

      - name: Build service
        run: |
          cd service
          mvn play2:dist

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: maven-dependency-cache-${{ hashFiles('**/pom.xml') }}
