name: pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: --entrypoint "/usr/local/bin/docker-entrypoint.sh cassandra -f"

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          
      - name: Wait for Cassandra to be ready
        run: |
          until nc -z localhost 9042; do
            echo "Waiting for Cassandra..."
            sleep 5
          done
      
      - name: Run test cases
        run: mvn clean install
