name: pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test cases
        run: mvn clean install
